spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/trainingDB
    username: root
    password: rootpassword
    driverClassName: com.mysql.jdbc.Driver